model:
  base_model_name: "vinai/PhoGPT-4B-Chat"
  torch_dtype: "bfloat16"

data:
  dataset_name: "hungnm/vietnamese-medical-qa"
  prompt_template: "### Câu hỏi: {instruction}\n### Trả lời:"
  test_size: 0.1
  seed: 42
  max_samples: 4167
  max_seq_length: 1024
  paths:
    raw_data: "data/raw/hungnm_vietnamese-medical-qa.json"
    sft_train: "data/processed/sft_train.json"
    sft_validation: "data/processed/sft_validation.json"
    reft_dpo_dataset: "data/processed/dpo_dataset.jsonl"
    tvaft_intermediate_dir: "data/processed/tvaft_intermediate"
    tvaft_01_model_responses: "data/processed/tvaft_intermediate/01_model_responses.csv"
    tvaft_02_judgements: "data/processed/tvaft_intermediate/02_judgements.csv"
    tvaft_03_bert_labels: "data/processed/tvaft_intermediate/03_bert_labels.csv"
    tvaft_final_dataset: "data/processed/tvaft_intermediate/tvaft_finetune_dataset.json"

quantization:
  load_in_4bit: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: false

peft:
  r: 16
  lora_alpha: 32
  target_modules:
    - "Wqkv"
    - "out_proj"
    - "up_proj"
    - "down_proj"
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"