model:
  new_adapter_name: "phogpt-4b-reft-dpo-adapter"
  final_model_name: "phogpt-4b-medical-chatbot-reft"
  base_model_name: "vinai/PhoGPT-4B-Chat"
  torch_dtype: "bfloat16"

data:
  dataset_name: "hungnm/vietnamese-medical-qa"
  prompt_template: "### Câu hỏi: {instruction}\n### Trả lời:"
  test_size: 0.1
  seed: 42
  max_samples: 4167
  max_seq_length: 1024
  paths:
    raw_data: "data/raw/hungnm_vietnamese-medical-qa.json"
    reft_dpo_dataset: "data/processed/dpo_dataset.jsonl"
    judgments_path: "data/processed/tvaft_intermediate/02_judgements.csv"
    model_responses_path: "data/processed/tvaft_intermediate/01_model_responses.csv"

quantization:
  load_in_4bit: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: false

peft:
  r: 16
  lora_alpha: 32
  target_modules:
    - "Wqkv"
    - "out_proj"
    - "up_proj"
    - "down_proj"
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  beta: 0.1

  output_dir: "./results/reft_dpo_training"
  num_train_epochs: 1
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 5.0e-6
  optim: "paged_adamw_32bit"

  evaluation_strategy: "steps"
  eval_steps: 100
  save_strategy: "steps"
  save_steps: 100
  save_total_limit: 2
  load_best_model_at_end: true

  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1

  report_to: "tensorboard"