model:
  new_model_name: "phogpt-4b-medical-chatbot-sft" # Tên thư mục lưu model SFT

training:
  output_dir: "./results/sft_training" # Thư mục lưu checkpoint
  num_train_epochs: 1
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  optim: "paged_adamw_32bit"

  evaluation_strategy: "steps"
  eval_steps: 100
  save_strategy: "steps"
  save_steps: 100
  save_total_limit: 2
  load_best_model_at_end: true

  learning_rate: 5.0e-5
  weight_decay: 0.01
  max_grad_norm: 0.3
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"

  report_to: "tensorboard"
  remove_unused_columns: true